### ISSUE TITLE
Django 3.2 Release

### ISSUE THREAD

**Issue by cmltaWt0** [rlucioni/pytest-django-ordering#14]
This issue is a proposal for Django 3.2 compatibility release.

@rlucioni Do you have plans for such a release in general?

Thanks.

**Comment by rlucioni** [comment]
Hey @cmltaWt0! I don't have plans for Django 3.2 compatibility, but if you know what changes are necessary, I'd be happy to accept a PR and ship a new version to PyPI.

**Comment by cmltaWt0** [comment]
@rlucioni Thanks. I'll try to find some time to analyze and come back with PR or suggestions.

**Comment by cmltaWt0** [comment]
Closing the issue for two reasons:

- actually the package works fine for Django3.2, there is no need to any special upgrade
- with the new version of pytest-django there is no need to use the package, ordering logic is added to the core by default
