### ISSUE TITLE
pytest 3.6 support

### ISSUE THREAD

**Issue by ostcar** [rlucioni/pytest-django-ordering#3]
I am new to pytest, so maybe I misunderstand something.

I installed your plugin and got:

```
...
TERNALERROR>   File ".../site-packages/pytest_django_ordering/plugin.py", line 13, in get_marker_transaction
INTERNALERROR>     return marker.transaction
INTERNALERROR> AttributeError: 'MarkInfo' object has no attribute 'transaction'
```
I could fix this by replacing `marker.transaction` with `marker.kwargs['transaction']`

**Comment by rlucioni** [comment]
Thanks for the heads-up @ostcar. Assuming that change also works for older versions of pytest, I'd be happy to accept a PR.

**Comment by rlucioni** [comment]
@ostcar just wanted to let you know that this has been fixed.
