### ISSUE TITLE
Incompatibilty with Pytest 5.*

### ISSUE THREAD

**Issue by macher91** [rlucioni/pytest-django-ordering#9]
I got errors:
`INTERNALERROR>   File "/root/.cache/pypoetry/virtualenvs/forge-api-py3.6/lib64/python3.6/site-packages/pytest_django_ordering/plugin.py", line 49, in pytest_collection_modifyitems
INTERNALERROR>     items.sort(key=weight_test_case)
INTERNALERROR>   File "/root/.cache/pypoetry/virtualenvs/forge-api-py3.6/lib64/python3.6/site-packages/pytest_django_ordering/plugin.py", line 39, in weight_test_case
INTERNALERROR>     elif has_fixture(test, 'db'):
INTERNALERROR>   File "/root/.cache/pypoetry/virtualenvs/forge-api-py3.6/lib64/python3.6/site-packages/pytest_django_ordering/plugin.py", line 27, in has_fixture
INTERNALERROR>     funcargnames = getattr(test, 'funcargnames', None)
INTERNALERROR>   File "/root/.cache/pypoetry/virtualenvs/forge-api-py3.6/lib64/python3.6/site-packages/_pytest/compat.py", line 331, in funcargnames
INTERNALERROR>     warnings.warn(FUNCARGNAMES, stacklevel=2)
INTERNALERROR> pytest.PytestDeprecationWarning: The `funcargnames` attribute was an alias for `fixturenames`, since pytest 2.3 - use the newer attribute instead.`

With version 4.* of pytests everything was ok

**Comment by rlucioni** [comment]
Should be fixed by https://github.com/rlucioni/pytest-django-ordering/pull/10. I'll update here once 1.2.0 is shipped. Thanks for the heads up.

**Comment by rlucioni** [comment]
@macher91 1.2.0 is shipped and should fix this issue. Thanks again for letting me know.
